### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by btb** [uw-it-aca/authz_group#12]
Are there plans to update this module to Django 2.0, or is it obsolete?

**Comment by jlaney** [comment]
I'm not ready to call it obsolete yet, but we're removing it as a dependency from projects as we upgrade them to Django 2.0.

**Comment by btb** [comment]
generally by using https://github.com/uw-it-aca/uw-django-saml2 instead?

**Comment by jlaney** [comment]
Yes, apps that have switched over to that library are using groups attributes for their authorization.

**Comment by btb** [comment]
thanks
